#!/usr/bin/env python3
"""Package verified Release binaries; requires Python 3.10+, Git and the pinned .NET SDK.

build.yaml is JSON-compatible YAML and owns descriptive release metadata. The project
owns the source version/framework/Jellyfin package ABI; duplicated build descriptor
fields must agree. Dates derive from SOURCE_DATE_EPOCH or the source commit, never
wall-clock time. Plugin code is never loaded: PackageVerifier reads PE metadata.
SIPHON_SOURCE_ROOT selects a separate historical source checkout; tooling stays here.
Historical projects can import tools/PackageVerifier/Provenance.targets explicitly.
"""
import argparse
from datetime import datetime, timezone
import hashlib
import json
import os
from pathlib import Path
import re
import subprocess
import tempfile
from urllib.parse import urlsplit
import xml.etree.ElementTree as ET
import zipfile

TOOL_ROOT = Path(__file__).resolve().parent.parent
ROOT = Path(os.environ.get("SIPHON_SOURCE_ROOT", str(TOOL_ROOT))).resolve()
PROJECT_DIR = ROOT / "src/Jellyfin.Plugin.Siphon"
PROJECT = PROJECT_DIR / "Jellyfin.Plugin.Siphon.csproj"
PLUGIN = "Jellyfin.Plugin.Siphon.dll"
PROVENANCE = "build-provenance.json"


def run(*command, cwd=ROOT):
    result = subprocess.run(command, cwd=cwd, text=True, capture_output=True, check=False)
    if result.returncode:
        raise ValueError(f"{' '.join(map(str, command))} failed: {result.stderr.strip() or result.stdout.strip()}")
    return result.stdout.strip()


def revision():
    return run("git", "rev-parse", "HEAD")


def source_digest():
    """Hash source paths/content, excluding generated output and machine-specific state."""
    excluded = {"bin", "obj", ".git", "__pycache__"}
    files = [p for p in PROJECT_DIR.rglob("*") if p.is_file()
             and not excluded.intersection(p.relative_to(PROJECT_DIR).parts)]
    files.extend(ROOT / name for name in (
        "manifest.json", "build.yaml", "global.json", "Directory.Build.props",
        "Directory.Build.targets", "Directory.Packages.props", "NuGet.Config",
        "NuGet.config", "nuget.config", "LICENSE") if (ROOT / name).is_file())
    files.extend(path for path in (ROOT / "assets").glob("*.png") if path.is_file())
    digest = hashlib.sha256()
    for path in sorted(set(files), key=lambda item: item.relative_to(ROOT).as_posix()):
        if path.is_symlink():
            raise ValueError(f"Source input must not be a symbolic link: {path.relative_to(ROOT)}")
        digest.update(path.relative_to(ROOT).as_posix().encode("utf-8") + b"\0")
        digest.update(hashlib.sha256(path.read_bytes()).digest())
    return digest.hexdigest()


def write_build_provenance(path):
    # Called before CoreCompile. Do not inspect/build the plugin from this path.
    content = ('// Generated by scripts/package.py; no timestamps or absolute paths.\n'
               f'[assembly: System.Reflection.AssemblyMetadata("SiphonSourceDigest", "{source_digest()}")]\n'
               f'[assembly: System.Reflection.AssemblyMetadata("SiphonSourceRevision", "{revision()}")]\n')
    path.parent.mkdir(parents=True, exist_ok=True)
    if not path.exists() or path.read_text(encoding="utf-8") != content:
        path.write_text(content, encoding="utf-8")


def load_descriptor():
    text = (ROOT / "build.yaml").read_text(encoding="utf-8")
    if text.lstrip().startswith("{"):
        return json.loads(text)
    # Historical tags used only scalar keys, a filename list and a literal
    # changelog. Accept that exact YAML subset, not arbitrary YAML constructs.
    def scalar(value):
        if value.startswith('"'):
            return json.loads(value)
        if value.startswith("'") and value.endswith("'"):
            return value[1:-1].replace("''", "'")
        if not value or value.startswith(("[", "{", "&", "*", "!", "|", ">")):
            raise ValueError("Unsupported historical build.yaml scalar; use JSON-compatible YAML for new releases")
        return value

    result, active, literal = {}, None, False
    for line in text.splitlines():
        if not line.strip() or line.lstrip().startswith("#"):
            if literal and not line.strip():
                result[active] += "\n"
            continue
        if line.startswith("  "):
            if literal:
                result[active] += line[2:] + "\n"
            elif active == "artifacts" and line.startswith("  - "):
                result[active].append(scalar(line[4:].strip()))
            else:
                raise ValueError("Unsupported nested historical build.yaml field")
            continue
        match = re.fullmatch(r"([A-Za-z][A-Za-z0-9]*):(?:[ ]+(.*))?", line)
        if match is None or match[1] in result:
            raise ValueError("Invalid or duplicate historical build.yaml field")
        active, value = match[1], (match[2] or "").strip()
        literal = value in ("|", "|-")
        if literal:
            result[active] = ""
        elif active == "artifacts" and not value:
            result[active] = []
        else:
            result[active] = scalar(value)
    if isinstance(result.get("changelog"), str):
        result["changelog"] = result["changelog"].rstrip("\n")
    return result


def descriptor():
    project = ET.parse(PROJECT).getroot()
    settings = {item.tag: item.text for group in project.findall("PropertyGroup") for item in group}
    metadata = load_descriptor()
    version = settings.get("Version", "")
    if not re.fullmatch(r"\d+\.\d+\.\d+\.\d+", version):
        raise ValueError("Project Version must contain four numeric components")
    if any(int(part) > 65534 for part in version.split(".")):
        raise ValueError("Project Version components must fit an assembly identity (0..65534)")
    for field, value in (("version", version), ("framework", settings.get("TargetFramework"))):
        if metadata.get(field) != value:
            raise ValueError(f"build.yaml {field} must match project: {value}")
    references = {item.attrib["Include"]: item.attrib.get("Version", "")
                  for item in project.findall("ItemGroup/PackageReference") if "Include" in item.attrib}
    if not references or any(not re.fullmatch(r"\d+\.\d+\.\d+(?:\.\d+)?", value) for value in references.values()):
        raise ValueError("Release builds require explicit stable direct dependency versions")
    jellyfin = {name: value for name, value in references.items() if name.startswith("Jellyfin.")}
    if not jellyfin or len(set(jellyfin.values())) != 1:
        raise ValueError("Jellyfin package references must use one explicit ABI version")
    abi = next(iter(jellyfin.values()))
    abi = abi + ".0" if abi.count(".") == 2 else abi
    if metadata.get("targetAbi") != abi:
        raise ValueError(f"build.yaml targetAbi must match Jellyfin package references: {abi}")
    for field in ("name", "guid", "imageUrl", "owner", "overview", "description", "category", "changelog"):
        if not isinstance(metadata.get(field), str) or not metadata[field].strip():
            raise ValueError(f"Missing release descriptor field: {field}")
    artifacts = metadata.get("artifacts")
    if not isinstance(artifacts, list) or not all(isinstance(item, str) for item in artifacts) or len(set(artifacts)) != len(artifacts):
        raise ValueError("build.yaml artifacts must be a unique list of archive names")
    return metadata, references


def image_file(metadata):
    filename = Path(urlsplit(metadata["imageUrl"]).path).name
    path = ROOT / "assets" / filename
    if path.suffix != ".png" or not path.is_file() or path.is_symlink():
        raise ValueError("The release image must name a regular PNG in assets/")
    return path


def release_tag(metadata):
    parts = metadata["version"].split(".")
    if parts[3] != "0":
        raise ValueError("Release tags use vMajor.Minor.Patch; the fourth assembly component must be zero")
    return "v" + ".".join(parts[:3])


def build_timestamp(value=None):
    if value:
        parsed = datetime.fromisoformat(value.replace("Z", "+00:00"))
        if parsed.tzinfo is None:
            raise ValueError("--timestamp must include a timezone")
    else:
        epoch = os.environ.get("SOURCE_DATE_EPOCH") or run("git", "show", "-s", "--format=%ct", "HEAD")
        parsed = datetime.fromtimestamp(int(epoch), timezone.utc)
    return parsed.astimezone(timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z")


def zip_timestamp(timestamp):
    # DOS dates cannot represent Unix epoch dates and only retain even seconds.
    date = datetime.fromisoformat(timestamp.replace("Z", "+00:00"))
    date = max(datetime(1980, 1, 1, tzinfo=timezone.utc),
               min(datetime(2107, 12, 31, 23, 59, 58, tzinfo=timezone.utc), date))
    return (date.year, date.month, date.day, date.hour, date.minute, date.second // 2 * 2)


def inspect(paths):
    verifier = TOOL_ROOT / "tools/PackageVerifier/PackageVerifier.csproj"
    run("dotnet", "build", str(verifier), "--configuration", "Release", "--nologo", "--verbosity", "quiet")
    executable = verifier.parent / "bin/Release/net10.0/PackageVerifier.dll"
    inspected = json.loads(run("dotnet", str(executable), *(str(path) for path in paths)))
    return {str(Path(item["path"]).resolve()): item for item in inspected}


def restored_inputs(metadata, references, build=None):
    assets_file = PROJECT_DIR / "obj/project.assets.json"
    if not assets_file.is_file():
        raise ValueError("Missing project.assets.json; restore and build the Release project first")
    assets = json.loads(assets_file.read_text(encoding="utf-8"))
    target = assets["targets"][metadata["framework"]]
    packages = {name.split("/")[0].lower(): (name, item)
                for name, item in target.items() if item.get("type") == "package"}
    for name, version in references.items():
        if packages.get(name.lower(), (None,))[0] != f"{name}/{version}":
            raise ValueError(f"Restore is stale for {name}/{version}; rebuild before packaging")

    def cached(key, asset):
        package_path = assets["libraries"][key]["path"]
        found = next((Path(folder) / package_path / asset for folder in assets["packageFolders"]
                      if (Path(folder) / package_path / asset).is_file()), None)
        if found is None:
            raise ValueError(f"Missing restored dependency input: {key}/{asset}")
        return found

    build = build or PROJECT_DIR / "bin/Release" / metadata["framework"]
    pending, visited, payload, runtime_paths = ["monotorrent"], set(), {}, []
    while pending:
        name = pending.pop()
        if name in visited:
            continue
        visited.add(name)
        if name not in packages:
            raise ValueError(f"Missing runtime dependency package: {name}")
        key, package = packages[name]
        pending.extend(dependency.lower() for dependency in package.get("dependencies", {}))
        if package.get("runtimeTargets"):
            raise ValueError(f"RID-specific runtime assets need an explicit packaging policy: {key}")
        for asset in package.get("runtime", {}):
            if asset.endswith("/_._"):
                continue
            filename = Path(asset).name
            data = (build / filename).read_bytes()
            if data != cached(key, asset).read_bytes():
                raise ValueError(f"Stale or modified runtime dependency: {filename}; rebuild before packaging")
            if filename in payload:
                raise ValueError(f"Conflicting runtime dependency filename: {filename}")
            payload[filename] = data
            runtime_paths.append(build / filename)
        license_file = next((cached(key, candidate) for candidate in assets["libraries"][key]["files"]
                             if Path(candidate).name.lower() in ("license", "license.md", "license.txt", "licence")), None)
        if license_file is None:
            raise ValueError(f"Missing dependency license for {key}")
        payload[f"licenses/{key.split('/')[0]}.txt"] = license_file.read_bytes()
    server_paths = []
    for name, (key, package) in packages.items():
        if name not in visited:
            server_paths.extend(cached(key, asset) for asset in package.get("compile", {})
                                if asset.endswith(".dll"))
    return build, payload, runtime_paths, server_paths


def verified_payload(metadata, references, build=None):
    build, payload, runtime_paths, server_paths = restored_inputs(metadata, references, build)
    dll = build / PLUGIN
    if not dll.is_file():
        raise ValueError("Missing Release plugin DLL; build before packaging")
    identities = inspect([dll, *runtime_paths, *server_paths])
    plugin = identities[str(dll.resolve())]
    if plugin["identity"]["name"] != Path(PLUGIN).stem or plugin["identity"]["version"] != metadata["version"]:
        raise ValueError(f"Plugin DLL identity/version {plugin['identity']} does not match project {metadata['version']}; rebuild before packaging")
    expected_framework = ".NETCoreApp,Version=v" + metadata["framework"][3:]
    if plugin["attributes"].get("System.Runtime.Versioning.TargetFrameworkAttribute") != expected_framework:
        raise ValueError("Plugin DLL target framework does not match the project; rebuild before packaging")
    digest, commit = source_digest(), revision()
    for attribute, value in (("SiphonSourceDigest", digest), ("SiphonSourceRevision", commit)):
        if plugin["attributes"].get(attribute) != value:
            raise ValueError(f"Plugin DLL {attribute} is missing or stale; rebuild the current source before packaging")
    available = {}
    for path in [*runtime_paths, *server_paths]:
        identity = identities[str(path.resolve())]["identity"]
        previous = available.setdefault(identity["name"], identity)
        if previous != identity:
            raise ValueError(f"Conflicting restored assembly identities: {identity['name']}")
    checked_references = {}
    for path in [dll, *runtime_paths]:
        item = identities[str(path.resolve())]
        for reference in item["references"]:
            name = reference["name"]
            if name in available:
                if reference != available[name]:
                    raise ValueError(f"ABI mismatch: {path.name} requires {reference}, restored identity is {available[name]}")
                checked_references[name] = reference
            elif not (name in ("mscorlib", "netstandard", "System", "Microsoft.CSharp")
                      or name.startswith(("System.", "Microsoft.Extensions.", "Microsoft.AspNetCore.", "Microsoft.Net.", "Microsoft.Win32."))):
                raise ValueError(f"Unresolved non-framework assembly reference in {path.name}: {name}")
    image = image_file(metadata)
    expected_files = {PLUGIN, image.name, *(path.name for path in runtime_paths)}
    if expected_files != set(metadata["artifacts"]):
        raise ValueError(f"build.yaml artifacts differs from runtime closure: expected {sorted(expected_files)}")
    payload.update({PLUGIN: dll.read_bytes(), "LICENSE": (ROOT / "LICENSE").read_bytes(),
                    image.name: image.read_bytes()})
    provenance = {"schemaVersion": 1, "sourceRevision": commit, "sourceDigest": digest,
                  "assembly": plugin["identity"],
                  "dependencies": sorted(checked_references.values(), key=lambda item: item["name"]),
                  "files": {name: hashlib.sha256(data).hexdigest() for name, data in sorted(payload.items())}}
    # Restore files contain absolute paths; do not put their bytes/hash into reproducible output.
    payload[PROVENANCE] = json_bytes(provenance)
    return payload


def json_bytes(value):
    return (json.dumps(value, indent=2, ensure_ascii=False) + "\n").encode("utf-8")


def manifest_for(metadata, timestamp, archive, content, release_url):
    release = {"version": metadata["version"], "targetAbi": metadata["targetAbi"],
               "sourceUrl": release_url.rstrip("/") + "/" + archive,
               "checksum": hashlib.md5(content).hexdigest(), "timestamp": timestamp,
               "changelog": metadata["changelog"]}
    return [{key: metadata[key] for key in ("guid", "name", "description", "overview", "owner", "category", "imageUrl")}
            | {"versions": [release]}]


def verify_archive(output, release_url=None):
    metadata, references = descriptor()
    archive = output / f"siphon-{metadata['version']}.zip"
    manifest = json.loads((output / "manifest.json").read_text(encoding="utf-8"))
    if not isinstance(manifest, list) or len(manifest) != 1 or len(manifest[0].get("versions", [])) != 1:
        raise ValueError("Package manifest must contain exactly one plugin and one release")
    release = manifest[0]["versions"][0]
    timestamp = build_timestamp(release["timestamp"])
    meta = {key: metadata[key] for key in ("guid", "name", "description", "overview", "owner", "category", "version", "targetAbi")}
    meta.update(timestamp=timestamp, imagePath=image_file(metadata).name)
    with zipfile.ZipFile(archive) as bundle, tempfile.TemporaryDirectory(prefix="siphon-verify-") as temporary:
        names = bundle.namelist()
        if len(names) != len(set(names)) or len(names) > 256 or sum(item.file_size for item in bundle.infolist()) > 128 * 1024 * 1024:
            raise ValueError("Archive has duplicate members or exceeds the package verification limits")
        expected_date = zip_timestamp(timestamp)
        for entry in bundle.infolist():
            if (entry.create_system != 3 or entry.external_attr >> 16 != 0o100644
                    or entry.flag_bits & 1 or entry.compress_type != zipfile.ZIP_DEFLATED
                    or entry.date_time != expected_date):
                raise ValueError(f"Archive member has unexpected type, permissions, compression or timestamp: {entry.filename}")
        binaries = Path(temporary)
        # Inspect the archive's PE files, not a rebuilt DLL. This permits recovery
        # with the original artifact even after the SDK has moved to a new patch.
        for name in metadata["artifacts"]:
            if "/" in name or "\\" in name or name in (".", ".."):
                raise ValueError("build.yaml artifacts must contain plain filenames")
            if name.endswith(".dll"):
                (binaries / name).write_bytes(bundle.read(name))
        expected = verified_payload(metadata, references, binaries)
        expected["meta.json"] = json_bytes(meta)
        if set(names) != set(expected):
            raise ValueError(f"Archive contents do not match the expected runtime closure: {archive}")
        for name, data in expected.items():
            if bundle.read(name) != data:
                raise ValueError(f"Archive member does not match verified source/build: {name}")
    url = release_url or default_release_url(metadata)
    if manifest != manifest_for(metadata, timestamp, archive.name, archive.read_bytes(), url):
        raise ValueError("Manifest metadata, source URL or archive checksum does not match the verified package")
    expected_sums = checksums(output, [archive.name, "manifest.json"])
    if (output / "SHA256SUMS").read_text(encoding="utf-8") != expected_sums:
        raise ValueError("SHA256SUMS does not match the verified archive and manifest")
    return metadata, manifest


def default_release_url(metadata):
    repository = ET.parse(PROJECT).getroot().findtext("PropertyGroup/RepositoryUrl")
    if not repository or not repository.startswith("https://github.com/"):
        raise ValueError("Project RepositoryUrl must identify the HTTPS GitHub repository")
    return repository.rstrip("/") + "/releases/download/" + release_tag(metadata)


def checksums(output, names):
    return "".join(hashlib.sha256((output / name).read_bytes()).hexdigest() + "  " + name + "\n" for name in names)


def package(output, release_url=None, timestamp=None):
    metadata, references = descriptor()
    payload = verified_payload(metadata, references)
    timestamp = build_timestamp(timestamp)
    release_url = release_url or default_release_url(metadata)
    meta = {key: metadata[key] for key in ("guid", "name", "description", "overview", "owner", "category", "version", "targetAbi")}
    meta.update(timestamp=timestamp, imagePath=image_file(metadata).name)
    payload["meta.json"] = json_bytes(meta)
    output.mkdir(parents=True, exist_ok=True)
    archive_name = f"siphon-{metadata['version']}.zip"
    zip_date = zip_timestamp(timestamp)
    with tempfile.TemporaryDirectory(prefix=".siphon-package-", dir=output) as temporary:
        staging = Path(temporary)
        archive = staging / archive_name
        with zipfile.ZipFile(archive, "w", compression=zipfile.ZIP_DEFLATED, compresslevel=9) as bundle:
            for name, data in sorted(payload.items()):
                entry = zipfile.ZipInfo(name, date_time=zip_date)
                entry.compress_type = zipfile.ZIP_DEFLATED
                entry.create_system = 3
                entry.external_attr = 0o100644 << 16
                bundle.writestr(entry, data, compress_type=zipfile.ZIP_DEFLATED, compresslevel=9)
        (staging / "manifest.json").write_bytes(json_bytes(manifest_for(metadata, timestamp, archive_name, archive.read_bytes(), release_url)))
        (staging / "SHA256SUMS").write_text(checksums(staging, [archive_name, "manifest.json"]), encoding="utf-8")
        for name in (archive_name, "manifest.json", "SHA256SUMS"):
            os.replace(staging / name, output / name)
    print(f"Verified package: {output / archive_name}")
    print(f"Unpublished catalog candidate: {output / 'manifest.json'}")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, default=ROOT / "artifacts")
    parser.add_argument("--release-url", help="Public URL prefix; default derives from project repository and version")
    parser.add_argument("--timestamp", help="Explicit ISO-8601 date; default SOURCE_DATE_EPOCH or source commit time")
    parser.add_argument("--write-build-provenance", type=Path, metavar="CS_FILE", help="Build hook: write source provenance attributes only, when changed")
    parser.add_argument("--verify-only", action="store_true", help="Validate existing ZIP, manifest, checksums, source and binary identities")
    args = parser.parse_args()
    try:
        if args.write_build_provenance:
            write_build_provenance(args.write_build_provenance)
        elif args.verify_only:
            verify_archive(args.output, args.release_url)
            print("Archive, source provenance, assembly identities and metadata verified")
        else:
            package(args.output, args.release_url, args.timestamp)
    except (OSError, ValueError, KeyError, TypeError, AttributeError, IndexError, OverflowError, ET.ParseError, zipfile.BadZipFile) as error:
        parser.exit(1, f"Packaging failed: {error}\n")


if __name__ == "__main__":
    main()
